networks:
  default:
    name: bambu-stats
    external: true
services:
  bambu-stats:
    image: chorn/bambu-stats:latest
    container_name: bambu-stats
    environment:
      printer_ip: 10.0.0.191
      printer_access_code: c12ff7f2
    working_dir: /app
    command: bash -c "openssl s_client -showcerts -connect $${printer_ip}:8883 </dev/null | sed -n -e '/-.BEGIN/,/-.END/ p' > blcert.pem && python bambu.py"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD=bambu-stats.json
  mysql:
    image: mysql:8.0
    container_name: mysql_bambu
    restart: always
    hostname: mysql_bambu
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: bambu
      MYSQL_PASSWORD: bambu
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql_bambu
      - PMA_PORT=3306
    ports:
      - 4646:80
volumes:
  grafana-data:
  db_data:
