apiVersion: 1
datasources:
  - name: mysql
    type: mysql
    access: proxy
    url: bs-mysql:3306
    database: bambu-stats
    user: root
    secureJsonData:
      password: pw
    isDefault: true
