{
 "title": "Bambu",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Percent Complete",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT mc_percent AS \"Percent Completed\" FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT mc_remaining_time FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT bed_temper FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Chamber Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT chamber_temper FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT nozzle_temper FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "AMS Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT ams_temper FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Aux Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT (big_fan1_speed/15)*100 FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Exhaust Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT (big_fan2_speed/15)*100 FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Part Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT (cooling_fan_speed/15)*100 FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "AMS Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`bambu-stats`",
     "rawSql": "SELECT ams_humidity FROM `bambu-stats`.stats ORDER BY id DESC LIMIT 1 "
    }
   ]
  }
 ]
}